name: Kernel + TEE Module Builder
on:
  workflow_dispatch:

jobs:
  kernel-build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          repository: whitewhale0612/android_kernel_common_oneplus_sm8750
          ref: v11
          path: kernel_source

      - name: Checkout module source
        uses: actions/checkout@v4
        with:
          path: module_source

      - name: Check branch info
        run: |
          cd kernel_source
          echo "当前分支: $(git branch --show-current)"
          echo "HEAD commit: $(git rev-parse HEAD)"
          cd ~

      - name: Setup zyclang Toolchain
        run: |
          echo "正在克隆zyClang19工具链..."
          mkdir -p clang
          aria2c -s16 -x16 -k1M https://github.com/ZyCromerZ/Clang/releases/download/19.0.0git-20240723-release/Clang-19.0.0git-20240723.tar.gz -o clang.tar.gz
          tar -xzf clang.tar.gz -C clang

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git make python3 flex bison libssl-dev libncurses-dev \
            bc rsync kmod cpio lbzip2 device-tree-compiler \
            libelf-dev ccache pahole
          sudo apt install -y aria2

      - name: Configure & Build Kernel
        run: |
          WORKDIR="$(pwd)"
          export PATH="$WORKDIR/clang/bin:$PATH"

          cd kernel_source
          make ARCH=arm64 SUBARCH=arm64 O=out \
            LLVM=1 \
            LLVM_IAS=1 \
            CC="clang" \
            CXX="clang++" \
            HOSTCC="clang" \
            HOSTCXX="clang++" \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            gki_defconfig

          make -j$(nproc) ARCH=arm64 SUBARCH=arm64 O=out \
            LLVM=1 \
            LLVM_IAS=1 \
            CC="clang" \
            CXX="clang++" \
            HOSTCC="clang" \
            HOSTCXX="clang++" \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi-

      - name: Build tz_tee_call module
        run: |
          WORKDIR="$(pwd)"
          export PATH="$WORKDIR/clang/bin:$PATH"

          cd kernel_source
          mkdir -p mymodule
          cp $WORKDIR/module_source/tz_tee_call.c mymodule/
          echo "obj-m += tz_tee_call.o" > mymodule/Makefile

          make -j$(nproc) ARCH=arm64 SUBARCH=arm64 O=out \
            LLVM=1 \
            LLVM_IAS=1 \
            CC="clang" \
            CXX="clang++" \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            M=$PWD/mymodule \
            modules

      - name: Pack AnyKernel3
        run: |
          git clone https://github.com/osm0sis/AnyKernel3.git AK3
          cp kernel_source/mymodule/tz_tee_call.ko AK3/
          cd AK3
          zip -r9 TZ_TEE_AK3.zip ./*

      - name: Upload All
        uses: actions/upload-artifact@v4
        with:
          name: SM8750_FULL_PACKAGE
          path: |
            kernel_source/out/arch/arm64/boot/Image.gz
            kernel_source/mymodule/tz_tee_call.ko
            AK3/TZ_TEE_AK3.zip
